const PDFDocument = require('pdfkit');
const pool = require('../config/db');

async function generateCertificate(batchId, res) {
  // Fetch batch + product
  const [batches] = await pool.query(
    `SELECT b.*, p.product_name 
     FROM Batches b 
     LEFT JOIN Products p ON b.product_id = p.product_id 
     WHERE b.batch_id = ?`,
    [batchId]
  );

  if (batches.length === 0) {
    throw new Error('Batch not found');
  }

  const batch = batches[0];

  // Fetch supply chain logs
  const [logs] = await pool.query(
    `SELECT * FROM SupplyChainLogs WHERE batch_id = ? ORDER BY timestamp ASC`,
    [batchId]
  );

  // Fetch certifications
  const [certs] = await pool.query(
    `SELECT * FROM Certifications WHERE batch_id = ?`,
    [batchId]
  );

  // Create PDF
  const doc = new PDFDocument({ margin: 50 });

  // Stream directly to response
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="AgriTrace-Certificate-Batch-${batchId}.pdf"`
  );
  doc.pipe(res);

  // ===== HEADER =====
  doc
    .fontSize(24)
    .fillColor('#15803d')
    .text('AgriTrace', { align: 'center' });

  doc
    .fontSize(12)
    .fillColor('#6b7280')
    .text('Farm to Table — Verified Supply Chain Certificate', { align: 'center' });

  doc.moveDown();

  // Divider
  doc
    .moveTo(50, doc.y)
    .lineTo(560, doc.y)
    .strokeColor('#e5e7eb')
    .stroke();

  doc.moveDown();

  // ===== CERTIFICATE TITLE =====
  doc
    .fontSize(18)
    .fillColor('#111827')
    .text('Supply Chain Certificate', { align: 'center' });

  doc
    .fontSize(12)
    .fillColor('#6b7280')
    .text(`Certificate No: AGT-${String(batchId).padStart(6, '0')}`, { align: 'center' });

  doc.moveDown();

  // ===== BATCH INFO =====
  doc
    .fontSize(14)
    .fillColor('#111827')
    .text('Batch Information', { underline: true });

  doc.moveDown(0.5);

  const info = [
    ['Product', batch.product_name || 'N/A'],
    ['Batch ID', `#${batch.batch_id}`],
    ['Quantity', `${batch.quantity} units`],
    ['Status', batch.status],
    ['Harvest Date', batch.harvest_date ? new Date(batch.harvest_date).toLocaleDateString() : '—'],
    ['Expiry Date', batch.expiry_date ? new Date(batch.expiry_date).toLocaleDateString() : '—'],
  ];

  info.forEach(([label, value]) => {
    doc
      .fontSize(11)
      .fillColor('#6b7280')
      .text(label + ':', { continued: true, width: 150 })
      .fillColor('#111827')
      .text(' ' + value);
  });

  doc.moveDown();

  // ===== SUPPLY CHAIN TIMELINE =====
  doc
    .fontSize(14)
    .fillColor('#111827')
    .text('Supply Chain Journey', { underline: true });

  doc.moveDown(0.5);

  if (logs.length === 0) {
    doc.fontSize(11).fillColor('#6b7280').text('No supply chain logs recorded.');
  } else {
    logs.forEach((log, index) => {
      doc
        .fontSize(11)
        .fillColor('#15803d')
        .text(`${index + 1}. ${log.stage}`, { continued: true })
        .fillColor('#6b7280')
        .text(`  —  ${new Date(log.timestamp).toLocaleString()}  |  ${log.status || 'N/A'}`);
    });
  }

  doc.moveDown();

  // ===== CERTIFICATIONS =====
  doc
    .fontSize(14)
    .fillColor('#111827')
    .text('Certifications', { underline: true });

  doc.moveDown(0.5);

  if (certs.length === 0) {
    doc.fontSize(11).fillColor('#6b7280').text('No certifications recorded.');
  } else {
    certs.forEach((cert) => {
      doc
        .fontSize(11)
        .fillColor('#111827')
        .text(`✓ ${cert.issued_by}`, { continued: true })
        .fillColor('#6b7280')
        .text(`  —  Issued: ${new Date(cert.issue_date).toLocaleDateString()}  |  Status: ${cert.status}`);
    });
  }

  doc.moveDown(2);

  // ===== FOOTER =====
  doc
    .moveTo(50, doc.y)
    .lineTo(560, doc.y)
    .strokeColor('#e5e7eb')
    .stroke();

  doc.moveDown(0.5);

  doc
    .fontSize(10)
    .fillColor('#9ca3af')
    .text(
      `Generated by AgriTrace on ${new Date().toLocaleString()}. This certificate verifies the complete supply chain journey of the above batch.`,
      { align: 'center' }
    );

  doc.end();
}

module.exports = { generateCertificate };